### ISSUE TITLE
Banks fail to load

### ISSUE THREAD

**Issue by MunchBunch3rd** [Mr-Unown/FMODStudioWrapperGMS2#6]
Hi, i tried this recently, but i ran into an issue, fmod dosent load the banks, if i have the fmod loader in a seperate room, it shows the errors, else it fails to compile, when i load in an event, this happens

**Comment by Mr-Unown** [comment]
Hello! May I ask for more information? Code snippets, screenshots, you name it.

**Comment by MunchBunch3rd** [comment]
i copied them over from your example, and modified it to work for my stuff

**Comment by MunchBunch3rd** [comment]
sounds/Desktop/Master.strings.bank :  1
FMOD error!(% d) % s
An invalid parameter was passed to this function.
sounds/Desktop/Master.bank :  3
FMOD error!(% d) % s
An invalid parameter was passed to this function.
sounds/Desktop/music.bank :  5
FMOD error!(% d) % s
An invalid parameter was passed to this function.
sounds/Desktop/sfx.bank :  7
FMOD error!(% d) % s
An invalid parameter was passed to this function.

code is mostly the same from the example

**Comment by MunchBunch3rd** [comment]
and this is if i load a sound from the banks

FMOD error!(% d) % s
An invalid object handle was used.
FMOD error!(% d) % s
An invalid object handle was used.

**Comment by MunchBunch3rd** [comment]
oh, it suddenly fixed itself

**Comment by Mr-Unown** [comment]
Ah well that's good then. Though would've liked to know exactly what was different.

**Comment by MunchBunch3rd** [comment]
I tried it on a different project again, and it didnt work again, but now i cant get it to fix itself. what should i try?

**Comment by Mr-Unown** [comment]
May I suggest you sending your project or like showing me your code, I would like to analyze it further.

**Comment by MunchBunch3rd** [comment]
https://www.mediafire.com/file/ubbq6ob4k0s2pts/PVZ_8_bit.zip/file

**Comment by MunchBunch3rd** [comment]
here

**Comment by MunchBunch3rd** [comment]
I figured out the solution. you might want to put it in the wiki or something:

Make sure that the FMOD object is persistent, else it will not work.

**Comment by Mr-Unown** [comment]
Ah ok, in that case, I will close this issue as resolved and will add to the wiki.
